download-external-modules: false
evaluate-variables: true
framework:
  - terraform
quiet: true
skip-check:
  - CKV_AWS_144 # See https://docs.bridgecrew.io/docs/ensure-that-s3-bucket-has-cross-region-replication-enabled
skip-path:
  - ./tests
